### ISSUE TITLE
Experiment: long-term memory recall

### ISSUE THREAD

**Issue by Pleasant-Cry** [anti-companion/koboldai-interceptor#7]
This idea is a bit vague, but we could implement an experiment where:

- Each statement in a bank of "long-term memories" is embedded using something like WordNet or Word2Vec and stored
- Statements in the prompt are embedded using the same approach
- A metric like cosine similarity is applied to determine semantic similarity between prompt statements and memories
- Top K memories exceeding some similarity threshold are injected into the prompt before sending to the LLM

**Comment by garrus0xff** [comment]
Or we can use sentence-transformers - https://www.sbert.net/examples/applications/semantic-search/README.html - ideally trying various approaches.

**Comment by Pleasant-Cry** [comment]
> Or we can use sentence-transformers - https://www.sbert.net/examples/applications/semantic-search/README.html - ideally trying various approaches.

Absolutely trying sentence-transformers right now -- thanks for putting that idea in my head. I posted some quick experimental results in the `model middleware` post channel on discord, if you're still around there. We miss you!
